### ISSUE TITLE
Some gear has no icon 

### ISSUE THREAD

**Issue by Aceship** [MurakumoIndustries/Gear#2]
https://murakumoindustries.github.io/Gear/#!/weapon/3667703682
![image](https://user-images.githubusercontent.com/5337323/49863781-9caa6500-fe33-11e8-8acc-abc75d517f09.png)

https://murakumoindustries.github.io/Gear/#!/weapon/566337086
![image](https://user-images.githubusercontent.com/5337323/49863795-a502a000-fe33-11e8-9244-57baa296d57d.png)

currently found 2 weapon that doesnt have icon

**Comment by WindWT** [comment]
fixed
